In [10]:
import pandas as pd
from dataset_manager import DatasetManager

In [7]:
dataset_path = "./datasets"
manager = DatasetManager(dataset_path)
dataset_identifier = "censo_rj_familias_2000"

In [8]:
manager.prepare_dataset()

05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing censo_rj_familias_2000 ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - censo_rj_familias_2000 is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing media_alunos_2008 ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - media_alunos_2008 is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing construcao_creche ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - construcao_creche is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing aprovacao_construcao_creche ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - aprovacao_construcao_creche is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing censo_rj_familias_2010 ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - censo_rj_familias_2010 is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing investimento_em_construcao_creche ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - investimento_em_construcao_creche is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing media_alunos_2010 ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - media_alunos_2010 is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing media_alunos_2009 ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - media_alunos_2009 is ready to use!
05-11 22:51 - DatasetManager - prepare_dataset - INFO - Preparing data_rio_2004_2008 ...
05-11 22:51 - DatasetManager - prepare_dataset - INFO - data_rio_2004_2008 is ready to use!

In [15]:
import os

In [16]:
os.listdir("./data/censo_2010/")

['tab4_19_2_5.xls',
 'tab4_19_1_3.xls',
 'tab4_19_1_5.xls',
 'tab4_19_1_1.xls',
 'tab4_19_2_1.xls',
 'tab4_19_2_4.xls',
 'tab4_19_1_2.xls',
 'tab4_19_2_3.xls',
 'tab4_19_1_4.xls',
 'tab4_19_2_2.xls']

In [17]:
pd.read_excel("./data/censo_2010/tab4_19_2_5.xls")

,Censo Demográfico 2010 - Características dos domicílios - Resultados da amostra,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Tabela 4.19.2.5 - Valor do rendimento nominal ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Mesorregiões,\nmicrorregiões\ne\nmunicípios",Valor do rendimento nominal mensal dos domicí...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Código\nda\nUnidade\nGeográfica
3,NaN,Médio,NaN,NaN,NaN,Mediano,NaN,NaN,NaN,NaN
4,NaN,Total ...,Adequação da moradia ...,NaN,NaN,Total ...,Adequação da moradia ...,NaN,NaN,NaN
5,NaN,NaN,Adequada ...,Semi-adequada ...,Inadequada ...,NaN,Adequada ...,Semi-adequada ...,Inadequada ...,NaN
6,Total,3011.11,3766.65,1755.8,1056.73,1530,1900,1200,810,33
7,Mesorregiões,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Baixadas,2370.87,2917.3,1854.28,1010.49,1500,1740,1210,850,3304
9,Centro Fluminense,2140.88,2477.59,1709.33,1076.73,1350,1530,1140,847,3303
10,Metropolitana do Rio de Janeiro,3206.85,4002.49,1788.16,1083.25,1590,2000,1210,820,3306
11,Noroeste Fluminense,1856.08,2109.69,1384.1,1133.84,1110,1300,1020,892,3301
12,Norte Fluminense,2273.31,3306.82,1475.77,907.758,1220,1800,1020,700,3302
13,Sul Fluminense,2389.67,2690.21,1744.18,1033.3,1526,1700,1210,800,3305
14,Microrregiões,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Bacia de São João,2713.32,3288.31,2211.61,942.492,1600,2000,1410,800,33009
16,Baía da Ilha Grande,2384.39,2706.74,1984.71,665.245,1530,1700,1421,660,33013
17,Barra do Piraí,2094.53,2441.48,1659.2,936.381,1350,1530,1110,680,33012
18,Campos dos Goytacazes,1959.26,2970.45,1311.35,806.781,1064,1534,1000,644,33003
19,Cantagalo-Cordeiro,1934.15,2148.58,1528.46,1506.72,1260,1404,1050,847,33006
20,Itaguaí,1975.39,2241.75,1726.64,1536.05,1326,1500,1200,1020,33017
21,Itaperuna,1923.97,2185.91,1368.25,1178.65,1200,1357,1020,942,33001
22,Lagos,2265.4,2808.7,1738.57,1027.66,1400,1700,1200,891,33010
23,Macacu-Caceribu,1863.72,2232.36,1574.83,1689.44,1200,1500,1058,1020,33016
24,Macaé,2960.09,3846.91,1943.71,1293.6,1624,2100,1310,1020,33004
25,Nova Friburgo,2329.42,2674.15,1926.31,940.477,1500,1610,1235,600,33007
26,Rio de Janeiro,3284.24,4076.02,1774.85,1037.89,1600,2000,1210,810,33018
27,Santa Maria Madalena,1486.66,1984.25,1298.27,1092.7,1020,1300,1020,1020,33008
28,Santo Antônio de Pádua,1748.29,1974.41,1404.56,1070.41,1020,1150,1020,815,33002
29,Serrana,2609.04,3197.13,2125.04,1064.54,1500,1710,1310,920,33015
...,...,...,...,...,...,...,...,...,...,...
98,Rio Claro,1880.1,2350.98,1518.53,1117.75,1200,1530,1020,1020,3304409
99,Rio das Flores,1681.06,1899.16,1428.75,2541.96,1164,1276,1020,2400,3304508
100,Rio das Ostras,3104.26,3746.54,2552.03,498.548,1900,2310,1600,407,3304524
101,Rio de Janeiro,4152.13,4755.29,2051.15,877.097,2000,2210,1384,690,3304557
102,Santa Maria Madalena,1511.07,2075.65,1197.05,1486.38,1020,1310,970,1120,3304607
103,Santo Antônio de Pádua,1929.27,2178.79,1513.11,1153.16,1110,1200,1020,825,3304706
104,São Fidélis,1629.06,1945.18,1137.72,1107.08,1020,1260,932,1020,3304805
105,São Francisco de Itabapoana,1079.52,1224.46,1084.39,843.361,710,1020,710,622,3304755
106,São Gonçalo,1961.05,2204.61,1659.36,1217.6,1420,1530,1210,1020,3304904
107,São João da Barra,1660.85,2098.43,1495.77,742.938,1020,1310,1020,540,3305000
108,São João de Meriti,1767.63,1883.77,1565.55,1016.48,1300,1310,1210,640,3305109
109,São José de Ubá,1191.06,1532.82,988.332,684.472,910,1020,800,512,3305133
110,São José do Vale do Rio Preto,1591.64,2066.3,1441.84,1110,1020,1300,1020,1110,3305158
111,São Pedro da Aldeia,2205.56,2545.85,1672.64,1000.2,1410,1650,1100,910,3305208
112,São Sebastião do Alto,1346.85,1672.91,1190.56,1011.22,1020,1220,1020,1020,3305307
113,Sapucaia,1713.91,2151.2,1253.59,526.72,1170,1430,1000,510,3305406
114,Saquarema,2070.63,2799.56,1903.46,853.796,1300,1900,1200,690,3305505
115,Seropédica,1871.99,2215.77,1545.92,1747.36,1300,1510,1110,1720,3305554
116,Silva Jardim,1447.38,1762.08,1338.57,1094.61,1020,1310,1000,900,3305604
117,Sumidouro,1385.26,1889.98,1305.85,728.25,1020,1400,1000,500,3305703
118,Tanguá,1313.66,1240.81,1327.97,1602.36,1020,1000,1020,1530,3305752
119,Teresópolis,2521.93,3362.92,1752.91,1122.2,1420,1770,1200,920,3305802
120,Trajano de Moraes,1578.25,2321.91,1449.02,870.532,1020,1420,1020,660,3305901
121,Três Rios,2263.07,2613.66,1497.61,1287.88,1459,1571,1110,1378,3306008
122,Valença,2061.36,2462.21,1533.58,821.998,1270,1530,1020,640,3306107
123,Varre-Sai,1379.24,1577.88,1256.55,1186.58,1020,1020,1020,1012,3306156
124,Vassouras,2082.81,2556.92,1516.81,679.853,1270,1500,1020,715,3306206
125,Volta Redonda,2760.26,2949.22,1748.66,998,1720,1820,1310,998,3306305
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,"Fonte: IBGE, Censo Demográfico 2010.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN